language: groovy
jdk:
- oraclejdk7
script: ./gradlew test
env:
  global:
  - secure: QHX7CnlV388994Tq4tvl1Og7ogqB8EnCP/Gn4SWJ21f1p7FXxy712tPgfl1kaOmb36IkxGwdAA/DEn+H47eMIbr3s9/itLKwlFOzIxKE/5rBpmoE6ZRMloH9K3ZG7nsRT+li72sBqaoW0KST1xCRS9zjGeYXjPPGElF02almaKY=
  - secure: RHWQJJ/jnxatDPJd3wQX41fTE5cbW0qfPFfHHcdS9EVBcSMMoFa44McUJmCGFX4WRG1jW6aIWmZqhQJr/f7S+aBA0+WhfwuYMheL7DfcxKg2UJ4EJDMtXBrjJinqGqIi9uEbuAPrUoEpOUA0DBhpd8tz5saf3sqcz+zteHjZCXQ=
after_success:
- '[[ $TRAVIS_BRANCH =~ ^(v[0-9]+\.[0-9]+\.[0-9]+|master)$ && $TRAVIS_PULL_REQUEST
  = false ]] && ./gradlew uploadArchives'
